# Generated by Django 5.0.3 on 2024-04-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('logo_image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('icon_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'address_city',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'address_street',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'address_street_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'phone_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.category',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'product_type',
                    models.CharField(
                        choices=[
                            ('PHYSICAL', 'physical'),
                            ('MONEY', 'money'),
                            ('BUNDLE', 'bundle'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=255)),
                ('link', models.TextField(blank=True, null=True)),
                ('main_image', models.TextField(blank=True, null=True)),
                ('gallery_images', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('cost_price', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                (
                    'product_size',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('SMALL', 'small'),
                            ('MEDIUM', 'medium'),
                            ('LARGE', 'large'),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('delivery_price', models.IntegerField(blank=True, null=True)),
                (
                    'logistics_rate_cost_percent',
                    models.IntegerField(blank=True, null=True),
                ),
                ('google_price', models.IntegerField(blank=True, null=True)),
                ('technical_details', models.TextField(blank=True, null=True)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('exchange_value', models.IntegerField(blank=True, null=True)),
                ('exchange_policy', models.TextField(blank=True, null=True)),
                (
                    'brand_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='brand_products',
                        to='inventory.brand',
                    ),
                ),
                (
                    'category',
                    models.ManyToManyField(
                        through='inventory.CategoryProduct', to='inventory.category'
                    ),
                ),
                (
                    'supplier_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='supplier_products',
                        to='inventory.supplier',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='product_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='inventory.product'
            ),
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('product_bundle_id', models.IntegerField()),
                (
                    'product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TagProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
                (
                    'tag_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='inventory.tag'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(
                through='inventory.TagProduct', to='inventory.tag'
            ),
        ),
    ]
