# Generated by Django 5.0.3 on 2024-05-02 10:30

from django.db import migrations

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0007_brand_name_en_brand_name_he_category_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
    ]
