# Generated by Django 5.0.3 on 2024-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0008_alter_brand_logo_image_alter_category_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
