# Generated by Django 5.0.3 on 2024-05-06 12:02

from django.db import migrations, models
import django.db.models.deletion

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('main', models.BooleanField(default=False)),
                (
                    'image',
                    lib.storage.RandomNameImageField(
                        upload_to=lib.storage.RandomNameImageField._generate_random_file_name
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_images',
                        to='inventory.product',
                    ),
                ),
            ],
        ),
    ]
