# Generated by Django 5.0.3 on 2024-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0011_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(
                choices=[
                    ('REGULAR', 'Regular'),
                    ('LARGE_PRODUCT', 'Large product'),
                    ('SENT_BY_SUPPLIER', 'Sent by supplier'),
                ],
                max_length=20,
            ),
        ),
    ]
