# Generated by Django 5.0.3 on 2024-05-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0013_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
