# Generated by Django 5.0.3 on 2024-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0016_alter_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(
                choices=[
                    ('PHYSICAL', 'physical'),
                    ('MONEY', 'money'),
                    ('BUNDLE', 'bundle'),
                ],
                default='PHYSICAL',
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
