# Generated by Django 5.0.6 on 2024-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0018_product_exchange_policy_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
