# Generated by Django 5.0.6 on 2024-06-29 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0019_alter_product_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
    ]
