# Generated by Django 5.0.6 on 2024-07-04 12:34

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.math


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0021_product_total_cost'),
    ]

    operations = [
        # remove and re-add since generated field expressions cannot be modified
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.math.Round(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Cast(
                                'cost_price', output_field=models.FloatField()
                            ),
                            '*',
                            models.Case(
                                models.When(
                                    models.Q(
                                        ('logistics_rate_cost_percent__isnull', True)
                                    ),
                                    then=models.Value(1.0),
                                ),
                                default=django.db.models.expressions.CombinedExpression(
                                    models.Value(1.0),
                                    '+',
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.functions.comparison.Cast(
                                            'logistics_rate_cost_percent',
                                            output_field=models.FloatField(),
                                        ),
                                        '/',
                                        models.Value(100.0),
                                    ),
                                ),
                            ),
                        ),
                        '+',
                        models.Case(
                            models.When(
                                models.Q(
                                    ('delivery_price__isnull', False),
                                    (
                                        'product_type__in',
                                        ('LARGE_PRODUCT', 'SENT_BY_SUPPLIER'),
                                    ),
                                ),
                                then=django.db.models.functions.comparison.Cast(
                                    'delivery_price', output_field=models.FloatField()
                                ),
                            ),
                            default=models.Value(0.0),
                        ),
                    ),
                    precision=1,
                ),
                output_field=models.FloatField(),
            ),
        ),
    ]
