# Generated by Django 5.0.6 on 2024-08-19 17:31

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0039_campaign_login_page_image_and_more'),
        ('inventory', '0025_product_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'share_id',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'share_type',
                    models.CharField(
                        choices=[('Product', 'Product'), ('Cart', 'Cart')],
                        max_length=20,
                        verbose_name='Share Type',
                    ),
                ),
                (
                    'campaign_code',
                    models.CharField(max_length=155, verbose_name='Campaign Code'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Updated At'),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='product_shares',
                        to='campaign.employee',
                        verbose_name='Owner',
                    ),
                ),
                (
                    'products',
                    models.ManyToManyField(
                        related_name='shares',
                        to='inventory.product',
                        verbose_name='Products',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
