# Generated by Django 5.0.6 on 2024-08-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0027_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
