# Generated by Django 5.0.6 on 2024-09-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0030_alter_product_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='supplier_products',
                to='inventory.supplier',
            ),
            preserve_default=False,
        ),
    ]
