# Generated by Django 5.0.6 on 2024-08-27 14:31

from django.db import migrations


def update_records(apps, schema_editor):
    product_model = apps.get_model('inventory', 'Product')
    brand_supplier_model = apps.get_model('inventory', 'BrandSupplier')

    for product in product_model.objects.all():
        brand = product.brand
        supplier = product.supplier
        brand_supplier = brand_supplier_model.objects.filter(
            brand=brand, supplier=supplier
        ).first()
        if not brand_supplier:
            brand_supplier = brand_supplier_model(brand=brand, supplier=supplier)
            brand_supplier.save()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0031_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(update_records),
    ]
