# Generated by Django 5.0.6 on 2024-09-09 12:34

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0034_data_migration_for_product_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 9, 12, 33, 59, 314991, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(
                default='',
                max_length=255,
                validators=[django.core.validators.EmailValidator()],
            ),
            preserve_default=False,
        ),
    ]
