# Generated by Django 5.0.6 on 2024-09-10 10:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0035_supplier_created_at_supplier_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 10, 10, 32, 49, 269226, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
