# Generated by Django 5.0.6 on 2024-09-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0036_brand_created_at_brand_is_deleted_brand_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundleitem',
            name='product_bundle_id',
        ),
        migrations.RemoveField(
            model_name='productbundleitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='bundled_products',
            field=models.ManyToManyField(
                through='inventory.ProductBundleItem', to='inventory.product'
            ),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='bundle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bundled_items',
                to='inventory.product',
            ),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bundles',
                to='inventory.product',
            ),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
