# Generated by Django 5.0.6 on 2024-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0037_remove_productbundleitem_product_bundle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_stock_sent',
            field=models.BooleanField(default=False),
        ),
    ]
