# Generated by Django 5.0.6 on 2024-09-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0038_product_alert_stock_sent'),
        ('logistics', '0012_logisticscenterstocksnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logistics_snapshot_stock_line',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='logistics.logisticscenterstocksnapshotline',
            ),
        ),
    ]
