# Generated by Django 5.0.6 on 2024-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0039_product_logistics_snapshot_stock_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
