# Generated by Django 5.0.6 on 2024-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0040_alter_supplier_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_kind',
            field=models.CharField(
                choices=[
                    ('PHYSICAL', 'physical'),
                    ('MONEY', 'money'),
                    ('BUNDLE', 'bundle'),
                    ('VARIATION', 'variation'),
                ],
                max_length=20,
            ),
        ),
    ]
