# Generated by Django 5.0.6 on 2024-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0040_alter_supplier_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SPECIAL_OFFER', 'Special Offer'),
                    ('BEST_VALUE', 'Best Value'),
                    ('LIMITED_TIME_OFFER', 'Limited Time Offer'),
                    ('JUST_LANDED', 'Just Landed'),
                    ('STAFF_PICK', 'Staff Pick'),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_en',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SPECIAL_OFFER', 'Special Offer'),
                    ('BEST_VALUE', 'Best Value'),
                    ('LIMITED_TIME_OFFER', 'Limited Time Offer'),
                    ('JUST_LANDED', 'Just Landed'),
                    ('STAFF_PICK', 'Staff Pick'),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_he',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SPECIAL_OFFER', 'Special Offer'),
                    ('BEST_VALUE', 'Best Value'),
                    ('LIMITED_TIME_OFFER', 'Limited Time Offer'),
                    ('JUST_LANDED', 'Just Landed'),
                    ('STAFF_PICK', 'Staff Pick'),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
