# Generated by Django 5.0.6 on 2024-10-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0050_quickofferselectedproduct_and_more'),
        ('inventory', '0041_product_offer_product_offer_en_product_offer_he'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='quick_offer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='campaign.quickoffer',
            ),
        ),
        migrations.AlterField(
            model_name='share',
            name='campaign_code',
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name='Campaign Code'
            ),
        ),
        migrations.AlterField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_shares',
                to='campaign.employee',
                verbose_name='Owner',
            ),
        ),
    ]
