# Generated by Django 5.0.6 on 2024-10-15 09:23

from django.db import migrations, models
import django.db.models.deletion

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0041_alter_product_product_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextVariation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('text_he', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'variation_kind',
                    models.CharField(
                        choices=[('TEXT', 'text'), ('COLOR', 'color')], max_length=10
                    ),
                ),
                ('system_name', models.CharField(max_length=255)),
                ('system_name_en', models.CharField(max_length=255, null=True)),
                ('system_name_he', models.CharField(max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('site_name_en', models.CharField(max_length=255, null=True)),
                ('site_name_he', models.CharField(max_length=255, null=True)),
                (
                    'color_variation',
                    models.ManyToManyField(
                        blank=True,
                        related_name='variations',
                        to='inventory.colorvariation',
                    ),
                ),
                (
                    'text_variation',
                    models.ManyToManyField(
                        blank=True,
                        related_name='text_variations',
                        to='inventory.textvariation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_enabled', models.BooleanField(default=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
                (
                    'variation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.variation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProductTextVariation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
                (
                    'product_variation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.productvariation',
                    ),
                ),
                (
                    'text',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.textvariation',
                    ),
                ),
                (
                    'variation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.variation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorVariationImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    lib.storage.RandomNameImageField(
                        upload_to=lib.storage.RandomNameImageField._generate_random_file_name
                    ),
                ),
                (
                    'color',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.colorvariation',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
                (
                    'product_variation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.productvariation',
                    ),
                ),
                (
                    'variation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.variation',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(
                related_name='products',
                through='inventory.ProductVariation',
                to='inventory.variation',
            ),
        ),
    ]
