# Generated by Django 5.0.6 on 2024-10-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0042_colorvariation_textvariation_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariationimage',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='color_variations',
                to='inventory.product',
            ),
        ),
        migrations.AlterField(
            model_name='producttextvariation',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='text_variations',
                to='inventory.product',
            ),
        ),
    ]
