# Generated by Django 5.0.6 on 2024-11-04 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0045_share_quick_offer_alter_share_campaign_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
    ]
