# Generated by Django 5.0.6 on 2024-11-11 11:45

from django.db import migrations

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0047_product_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariationimage',
            name='image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
    ]
