# Generated by Django 5.0.6 on 2024-12-06 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0048_alter_productcolorvariationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='client_discount_rate',
            field=models.FloatField(
                blank=True,
                help_text='Enter a Client Discount Rate up to 100.0.',
                null=True,
                validators=[django.core.validators.MaxValueValidator(100.0)],
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_discount_rate',
            field=models.FloatField(
                blank=True,
                help_text='Enter a Supplier Discount Rate up to 100.0.',
                null=True,
                validators=[django.core.validators.MaxValueValidator(100.0)],
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='voucher_type',
            field=models.CharField(
                blank=True,
                choices=[('PHYSICAL', 'physical'), ('DIGITAL', 'digital')],
                max_length=20,
                null=True,
            ),
        ),
    ]
