# Generated by Django 5.0.6 on 2025-02-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0050_alter_brand_name_alter_brand_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text='Use positive values normally. Negative values will cause the category to be displayed before the "All" category',  # noqa: E501
                null=True,
            ),
        ),
    ]
