# Generated by Django 5.0.6 on 2025-02-18 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0051_alter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(22)],
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(22)],
            ),
        ),
    ]
