# Generated by Django 5.0.6 on 2025-05-23 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0052_alter_product_reference_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(255)],
            ),
        ),
    ]
