# Generated by Django 5.0.6 on 2024-09-07 22:50

from django.db import migrations


PERMISSIONS_GROUP_NAME = 'Full Access Except Delete'


def create_group_with_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Create the group
    group, created = Group.objects.get_or_create(name=PERMISSIONS_GROUP_NAME)

    # Get all permissions except delete permissions
    all_permissions = Permission.objects.filter(
        content_type__in=ContentType.objects.all()
    ).exclude(codename__startswith='delete_')

    # Assign permissions to the group
    group.permissions.set(all_permissions)


def remove_group_with_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=PERMISSIONS_GROUP_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0003_usertwofactorauthdata'),
    ]

    operations = [
        migrations.RunPython(
            create_group_with_permissions, remove_group_with_permissions
        ),
    ]
