# Generated by Django 5.0.6 on 2024-07-27 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POOrder',
            fields=[],
            options={
                'verbose_name': 'PO Order',
                'verbose_name_plural': 'PO Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.purchaseorder',),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
