# Generated by Django 5.0.6 on 2024-07-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0003_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PurchaseOrderIntermediate',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'purchaseorder',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='logistics.purchaseorder',
                            ),
                        ),
                        (
                            'purchaseorderproduct',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='logistics.purchaseorderproduct',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'logistics_purchaseorder_products',
                        'unique_together': {('purchaseorder', 'purchaseorderproduct')},
                    },
                ),
                migrations.AlterField(
                    model_name='purchaseorder',
                    name='products',
                    field=models.ManyToManyField(
                        through='logistics.PurchaseOrderIntermediate',
                        to='logistics.purchaseorderproduct',
                    ),
                ),
            ]
        )
    ]
