# Generated by Django 5.0.6 on 2024-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'logistics',
            '0004_alter_purchaseorder_notes_purchaseorderintermediate_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
