# Generated by Django 5.0.6 on 2024-08-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0005_alter_purchaseorder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='products',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='logistics.purchaseorder',
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseOrderIntermediate',
        ),
    ]
