# Generated by Django 5.0.6 on 2024-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0006_remove_purchaseorder_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCenterMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'center',
                    models.CharField(choices=[('ORIAN', 'Orian')], max_length=100),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_body', models.TextField()),
            ],
        ),
    ]
