# Generated by Django 5.0.6 on 2024-08-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0007_logisticscentermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCenterInboundReceipt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'center',
                    models.CharField(choices=[('ORIAN', 'Orian')], max_length=100),
                ),
                ('receipt_code', models.CharField(max_length=16)),
                ('receipt_start_date', models.DateTimeField()),
                ('receipt_close_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_to_logistics_center_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='LogisticsCenterInboundReceiptLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('receipt_line', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                (
                    'logistics_center_message',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='logistics.logisticscentermessage',
                    ),
                ),
                (
                    'purchase_order_product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='logistics.purchaseorderproduct',
                    ),
                ),
                (
                    'receipt',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='logistics.logisticscenterinboundreceipt',
                    ),
                ),
            ],
        ),
    ]
