# Generated by Django 5.0.6 on 2024-08-19 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0008_logisticscenterinboundreceipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderproduct',
            old_name='quantity_in_transit',
            new_name='quantity_sent_to_logistics_center',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='quantity_in_dc',
        ),
    ]
