# Generated by Django 5.0.6 on 2024-08-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0040_order_logistics_center_status'),
        (
            'logistics',
            '0009_rename_quantity_in_transit_purchaseorderproduct_quantity_sent_to_logistics_center_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticscentermessage',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('INBOUND_RECEIPT', 'Inbound receipt'),
                    ('ORDER_STATUS_CHANGE', 'Order status change'),
                    ('SHIP_ORDER', 'Ship order'),
                ],
                default='INBOUND_RECEIPT',
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LogisticsCenterOrderStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'center',
                    models.CharField(choices=[('ORIAN', 'Orian')], max_length=100),
                ),
                ('status', models.CharField(max_length=16)),
                ('status_date_time', models.DateTimeField()),
                (
                    'logistics_center_message',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='logistics.logisticscentermessage',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='campaign.order'
                    ),
                ),
            ],
        ),
    ]
