# Generated by Django 5.0.6 on 2025-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0012_logisticscenterstocksnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
