# Generated by Django 5.0.6 on 2025-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0013_purchaseorderproduct_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticscenterinboundreceipt',
            name='center',
            field=models.CharField(
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='logisticscentermessage',
            name='center',
            field=models.CharField(
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='logisticscenterorderstatus',
            name='center',
            field=models.CharField(
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='logisticscenterstocksnapshot',
            name='center',
            field=models.CharField(
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
            ),
        ),
    ]
