# Generated by Django 5.0.6 on 2025-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0014_alter_logisticscenterinboundreceipt_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticscentermessage',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('INBOUND_RECEIPT', 'Inbound receipt'),
                    ('ORDER_STATUS_CHANGE', 'Order status change'),
                    ('SHIP_ORDER', 'Ship order'),
                    ('SNAPSHOT', 'Snapshot'),
                ],
                max_length=100,
            ),
        ),
    ]
