# Generated by Django 5.0.6 on 2025-02-05 10:54

from django.db import migrations, models
import django.db.models.deletion


def backfill_po_centers(apps, schema_editor):
    # backfill purchase order centers - any po that was sent to a logistics
    # center up until now was sent to orian
    PurchaseOrder = apps.get_model('logistics', 'PurchaseOrder')

    for po in PurchaseOrder.objects.filter(
        sent_to_logistics_center_at__isnull=False
    ).all():
        po.logistics_center = 'ORIAN'
        po.save()


def reverse_backfill_po_centers(apps, schema_editor):
    # no need to reverse this modification since the column will be deleted
    # when other operations are reversed
    return


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0015_alter_logisticscentermessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='logistics_center',
            field=models.CharField(
                blank=True,
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_po_centers, reverse_code=reverse_backfill_po_centers
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistics_center_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistics_center_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='logisticscenterinboundreceipt',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='logisticscenterinboundreceipt',
            name='receipt_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='logisticscenterinboundreceipt',
            name='receipt_close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logisticscenterorderstatus',
            name='status',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='LogisticsCenterInboundStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'center',
                    models.CharField(
                        choices=[
                            ('ORIAN', 'Orian'),
                            ('PICK_AND_PACK', 'Pick and Pack'),
                        ],
                        max_length=100,
                    ),
                ),
                ('status', models.CharField(max_length=32)),
                ('status_date_time', models.DateTimeField()),
                (
                    'logistics_center_message',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='logistics.logisticscentermessage',
                    ),
                ),
                (
                    'purchase_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='logistics.purchaseorder',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='logisticscentermessage',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('INBOUND_RECEIPT', 'Inbound receipt'),
                    ('ORDER_STATUS_CHANGE', 'Order status change'),
                    ('SHIP_ORDER', 'Ship order'),
                    ('SNAPSHOT', 'Snapshot'),
                    ('INBOUND_STATUS_CHANGE', 'Inbound status change'),
                ],
                max_length=100,
            ),
        ),
    ]
