# Generated by Django 5.0.6 on 2025-03-07 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0016_purchaseorder_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='voucher_value',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
