# Generated by Django 5.0.6 on 2025-06-03 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('logistics', '0017_add_voucher_value_to_purchaseorderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularOrderSummary',
            fields=[],
            options={
                'verbose_name': 'Order Summaries – Regular',
                'verbose_name_plural': 'Order Summaries – Regular',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.employeeorderproduct',),
        ),
        migrations.CreateModel(
            name='SupplierOrderSummary',
            fields=[],
            options={
                'verbose_name': 'Order Summaries – Sent by Supplier',
                'verbose_name_plural': 'Order Summaries – Sent by Supplier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.employeeorderproduct',),
        ),
        migrations.CreateModel(
            name='VoucherOrderSummary',
            fields=[],
            options={
                'verbose_name': 'Order Summaries – Vouchers',
                'verbose_name_plural': 'Order Summaries – Vouchers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logistics.employeeorderproduct',),
        ),
    ]
