# Generated by Django 5.0.6 on 2025-06-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0078_fill_voucher_val'),
        ('logistics', '0018_regularordersummary_supplierordersummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='order_product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='campaign.orderproduct',
            ),
        ),
    ]
