# Generated by Django 5.0.3 on 2024-06-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0021_remove_employeegroupcampaign_products_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinformation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='product',
        ),
        # note: since this was added before the platform graduated to
        # production there is no handling of existing PaymentInformation
        # objects here. if you do have any and can delete them go ahead and
        # then run this migration. if not add an intermediary step to add the
        # new field with nullable=True, fill your missing data and then alter
        # the field to be nullable=False
        migrations.AddField(
            model_name='paymentinformation',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='campaign.order'
            ),
            preserve_default=False,
        ),
    ]
