from django.urls import path

from . import views
from .admin_views import (
    CampaignEmployeeAutocompleteView,
    EmployeeGroupAutocompleteView,
    EmployeeGroupCampaignProductAutocompleteView,
    OrganizationAutocompleteView,
    PurchaseOrderProductAutocomplete,
    QuickOfferAutocompleteView,
    update_employee_budget,
)


urlpatterns = [
    path(
        '<str:campaign_code>/details',
        views.CampaignView.as_view(),
        name='compaign_details',
    ),
    path(
        '<str:campaign_code>/employee-selection',
        views.CampaignEmployeeSelectionView.as_view(),
        name='employee_selection',
    ),
    path(
        '<str:campaign_code>/categories',
        views.CampaignCategoriesView.as_view(),
        name='compaign_categories',
    ),
    path(
        'organization-groups/<int:organization_id>',
        views.EmployeeGroupView.as_view(),
        name='organization_groups',
    ),
    path(
        '<str:campaign_code>/order/details',
        views.OrderDetailsView.as_view(),
        name='order_details',
    ),
    path(
        '<str:campaign_code>/product/<int:product_id>/details/',
        views.ProductView.as_view(),
        name='product_details',
    ),
    path(
        '<str:campaign_code>/products/',
        views.CampaignProductsView.as_view(),
        name='campaign_products',
    ),
    path(
        '<str:campaign_code>/share/',
        views.ShareProductView.as_view(),
        name='campaign_products',
    ),
    path(
        'share/<str:share_id>/',
        views.GetShareDetailsView.as_view(),
        name='campaign_products',
    ),
    path(
        '<str:campaign_code>/login',
        views.EmployeeLoginView.as_view(),
        name='employee_login_view',
    ),
    path(
        '<str:campaign_code>/cancel/order/<int:order_id>',
        views.CancelOrderView.as_view(),
        name='cancel_order',
    ),
    path(
        'categories-suppliers-tags',
        views.CategoriesBrandsSuppliersTagsView.as_view(),
        name='categories_suppliers_tags',
    ),
    path(
        '<str:campaign_code>/order',
        views.EmployeeOrderView.as_view(),
        name='employee_order_view',
    ),
    path(
        'get-campaign/<str:employee_group_id>/',
        views.GetCampaignView.as_view(),
        name='get_campaign_view',
    ),
    path(
        '<str:campaign_code>/cart/add_product',
        views.CartAddProductView.as_view(),
        name='cart_add_product',
    ),
    path(
        '<str:campaign_code>/exchange',
        views.CampaignImpersonationTokenExhcangeView.as_view(),
        name='campaign_impersonation_token_exchange_view',
    ),
    path(
        '<str:quick_offer_code>/quick_offer_exchange',
        views.QuickOfferImpersonationTokenExhcangeView.as_view(),
        name='quick_offer_impersonation_token_exchange_view',
    ),
    path(
        '<str:campaign_code>/cart/products/',
        views.GetCartProductsView.as_view(),
        name='get_cart_products',
    ),
    path(
        'campaign-employee-autocomplete',
        CampaignEmployeeAutocompleteView.as_view(),
        name='campaign-employee-autocomplete',
    ),
    path(
        '<str:campaign_code>/filter_lookup',
        views.FilterLookupView.as_view(),
        name='filter_lookup',
    ),
    path(
        'quick-offer/<str:quick_offer_code>',
        views.OrganizationQuickOfferView.as_view(),
        name='organization-quick-offer',
    ),
    path(
        '<str:quick_offer_code>/quick-offer-login',
        views.OrganizationQuickOfferLoginView.as_view(),
        name='organization_quick_offer_login',
    ),
    path(
        'validate/<str:code>',
        views.ValidateCodeView.as_view(),
        name='validate_code',
    ),
    path(
        'quick-offer-products',
        views.QuickOfferProductsView.as_view(),
        name='quick_offer_products',
    ),
    path(
        'quick-offer-product/<int:product_id>',
        views.QuickOfferProductView.as_view(),
        name='quick_offer_product',
    ),
    path(
        'list/add_product',
        views.QuickOfferSelectProductsView.as_view(),
        name='quick_offer_select_products',
    ),
    path(
        'list/',
        views.GetQuickOfferSelectProductsView.as_view(),
        name='get_quick_offer_select_products',
    ),
    path(
        'quick-offer-categories',
        views.QuickOfferCategoriesView.as_view(),
        name='compaign_categories',
    ),
    path(
        'quick-offer-share/',
        views.QuickOfferShareView.as_view(),
        name='quick_offer_share',
    ),
    path(
        'get-quick-offer-share/<str:share_id>',
        views.GetQuickOfferShareView.as_view(),
        name='campaign_product',
    ),
    path(
        'organization/<int:organization_id>',
        views.OrganizationView.as_view(),
        name='organization_view',
    ),
    path(
        'send_my_list/',
        views.UpdateOrganizationQuickOfferView.as_view(),
        name='update send my list',
    ),
    path(
        'organization-product',
        views.OrganizationProductView.as_view(),
        name='organization_product',
    ),
    path(
        'update-employee-budget/<int:employee_id>/',
        update_employee_budget,
        name='update_employee_budget',
    ),
    path(
        'campaign-employee-send-invitation',
        views.CampaignEmployeeSendInvitationView.as_view(),
        name='campaign-employee-send-invitation',
    ),
    path(
        'admin/campaign/orderproduct/purchase-order-product-autocomplete/',
        PurchaseOrderProductAutocomplete.as_view(),
        name='purchase-order-product-autocomplete',
    ),
    path(
        'organization-autocomplete/',
        OrganizationAutocompleteView.as_view(),
        name='organization-autocomplete',
    ),
    path(
        'employee-group-campaign-product-autocomplete',
        EmployeeGroupCampaignProductAutocompleteView.as_view(),
        name='employee-group-campaign-product-autocomplete',
    ),
    path(
        'employee-group-autocomplete',
        EmployeeGroupAutocompleteView.as_view(),
        name='employee-group-autocomplete',
    ),
    path(
        'quick-offer-autocomplete',
        QuickOfferAutocompleteView.as_view(),
        name='quick-offer-autocomplete',
    ),
    path(
        'employee-group-campaign-product',
        views.EmployeeGroupCampaignProductView.as_view(),
        name='employee-group-campaign-product',
    ),
]
