# Generated by Django 5.0.3 on 2024-04-23 09:14

from django.db import migrations, models
import django.db.models.deletion

import campaign.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner_image', models.CharField(max_length=255)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('auth_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                (
                    'phone_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('birthday_date', models.DateField(blank=True, null=True)),
                (
                    'default_language',
                    models.CharField(
                        blank=True,
                        choices=[('EN', 'English'), ('HE', 'Hebrew')],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'delivery_city',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'delivery_street',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'delivery_street_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    'delivery_apartment_number',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('manager_full_name', models.CharField(max_length=255)),
                ('manager_phone_number', models.CharField(max_length=255)),
                ('manager_email', models.CharField(max_length=255)),
                ('logo_image', models.CharField(max_length=255)),
                (
                    'custom_text_font',
                    models.CharField(choices=[('ROBOTO', 'Roboto')], max_length=20),
                ),
                ('custom_text_color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEmployee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.campaign',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.employee',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('group_campaign_product_id', models.IntegerField()),
                (
                    'campaign_employee_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.campaignemployee',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'cart_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='campaign.cart'
                    ),
                ),
                (
                    'product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='employees',
            field=models.ManyToManyField(
                through='campaign.CampaignEmployee', to='campaign.employee'
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='campaign.employeegroup',
            ),
        ),
        migrations.CreateModel(
            name='EmployeeGroupCampaign',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('budget_per_employee', models.IntegerField()),
                ('organization_address_id', models.IntegerField()),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.campaign',
                    ),
                ),
                (
                    'employee_group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.employeegroup',
                    ),
                ),
                ('products', models.ManyToManyField(to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='campaigns',
            field=models.ManyToManyField(
                through='campaign.EmployeeGroupCampaign', to='campaign.campaign'
            ),
        ),
        migrations.CreateModel(
            name='EmployeeGroupCampaignProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'employee_group_campaign_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.employeegroupcampaign',
                    ),
                ),
                (
                    'product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('group_campaign_product_id', models.IntegerField()),
                ('order_date_time', models.DateTimeField()),
                ('cost_from_budget', models.IntegerField()),
                ('cost_added', models.IntegerField()),
                ('reference', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CANCELLED', 'Cancelled'),
                            ('SENT_TO_LOGISTIC_CENTER', 'Sent To Logistic Center'),
                        ],
                        default=campaign.models.Order.OrderStatusEnum['PENDING'],
                        max_length=50,
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('USD', 'usd'),
                            ('EUR', 'eur'),
                            ('GBP', 'gbp'),
                            ('JPY', 'jpy'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'campaign_employee_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.campaignemployee',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'order_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='campaign.order'
                    ),
                ),
                (
                    'product_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('price', models.IntegerField()),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.organization',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(
                through='campaign.OrganizationProduct', to='inventory.product'
            ),
        ),
    ]
