# Generated by Django 5.0.3 on 2024-04-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0002_employee_first_name_en_employee_first_name_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='campaign.organization',
            ),
        ),
    ]
