# Generated by Django 5.0.3 on 2024-04-29 10:08

from django.db import migrations, models

import campaign.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0003_employeegroup_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupcampaign',
            name='auth_method',
            field=models.CharField(
                choices=[('EMAIL', 'email'), ('SMS', 'sms'), ('AUTH_ID', 'auth_id')],
                default=campaign.models.EmployeeAuthEnum['SMS'],
                max_length=50,
            ),
        ),
    ]
