# Generated by Django 5.0.3 on 2024-05-02 10:30

from django.db import migrations

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0004_employeegroupcampaign_auth_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_image',
            field=lib.storage.RandomNameImageField(
                blank=True,
                null=True,
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
        ),
    ]
