# Generated by Django 5.0.3 on 2024-05-05 11:49

from django.db import migrations, models

import campaign.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0006_campaign_description_en_campaign_description_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(
                choices=[('EVENT', 'Event')],
                default=campaign.models.Campaign.CampaignTypeEnum['EVENT'],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ship_to',
            field=models.CharField(
                choices=[('TO_OFFICE', 'To Office'), ('TO_EMPLOYEES', 'To Employees')],
                default=campaign.models.Campaign.CampaignShippingEnum['TO_OFFICE'],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('OFFER', 'Offer'),
                    ('ACTIVE', 'Active'),
                    ('FINISHED', 'Finished'),
                ],
                default=campaign.models.Campaign.CampaignStatusEnum['PENDING'],
                max_length=30,
            ),
        ),
    ]
