# Generated by Django 5.0.3 on 2024-05-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0007_campaign_campaign_type_campaign_ship_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(max_length=255)),
                ('delivery_street', models.CharField(max_length=255)),
                ('delivery_street_number', models.CharField(max_length=255)),
                ('delivery_apartment_number', models.CharField(max_length=255)),
                (
                    'organization_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.organization',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='employeegroupcampaign',
            name='organization_address_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='campaign.organizationaddress',
            ),
        ),
    ]
