# Generated by Django 5.0.3 on 2024-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0009_employee_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('OFFER', 'Offer'),
                    ('ACTIVE', 'Active'),
                    ('FINISHED', 'Finished'),
                ],
                default='PENDING',
                max_length=30,
            ),
        ),
    ]
