# Generated by Django 5.0.3 on 2024-05-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0010_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegroupcampaign',
            name='organization_address_id',
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='delivery_apartment_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='delivery_street_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationAddress',
        ),
    ]
