# Generated by Django 5.0.3 on 2024-05-31 17:44

from django.db import migrations, models

import lib.phone_utils


class Migration(migrations.Migration):
    dependencies = [
        (
            'campaign',
            '0011_remove_employeegroupcampaign_organization_address_id_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[lib.phone_utils.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager_phone_number',
            field=models.CharField(
                max_length=255, validators=[lib.phone_utils.validate_phone_number]
            ),
        ),
    ]
