# Generated by Django 5.0.3 on 2024-06-06 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0013_remove_organization_custom_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='manager_email',
            field=models.CharField(
                max_length=255, validators=[django.core.validators.EmailValidator()]
            ),
        ),
    ]
