# Generated by Django 5.0.3 on 2024-06-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0014_alter_organization_manager_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='group_campaign_product_id',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='campaign.employeegroupcampaignproduct',
            ),
        ),
    ]
