# Generated by Django 5.0.3 on 2024-06-10 09:57

from django.db import migrations

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0017_alter_employeegroupcampaign_auth_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_image',
            field=lib.storage.RandomNameImageField(
                default='-',
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
            preserve_default=False,
        ),
    ]
