# Generated by Django 5.0.3 on 2024-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0018_alter_organization_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegroupcampaign',
            name='auth_method',
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='auth_method',
            field=models.CharField(
                choices=[('EMAIL', 'email'), ('SMS', 'sms'), ('AUTH_ID', 'auth_id')],
                default='EMAIL',
                max_length=50,
            ),
        ),
    ]
