# Generated by Django 5.0.3 on 2024-06-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0019_remove_employeegroupcampaign_auth_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='auth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
