# Generated by Django 5.0.3 on 2024-06-15 17:55

from django.db import migrations, models

import campaign.models
import lib.phone_utils


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0020_alter_employee_active_alter_employee_auth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegroupcampaign',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_additional_details',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_phone_number',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[lib.phone_utils.validate_phone_number],
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_apartment_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[lib.phone_utils.validate_phone_number],
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='reference',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('INCOMPLETE', 'Incomplete'),
                    ('PENDING', 'Pending'),
                    ('CANCELLED', 'Cancelled'),
                    ('SENT_TO_LOGISTIC_CENTER', 'Sent To Logistic Center'),
                ],
                default=campaign.models.Order.OrderStatusEnum['INCOMPLETE'],
                max_length=50,
            ),
        ),
    ]
