# Generated by Django 5.0.3 on 2024-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0021_remove_employeegroupcampaign_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='default_language',
            field=models.CharField(
                choices=[('EN', 'English'), ('HE', 'Hebrew')],
                default='HE',
                max_length=255,
            ),
        ),
    ]
