# Generated by Django 5.0.6 on 2024-06-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0022_alter_employee_default_language'),
    ]

    operations = [
        # we do not handle existing employees with NULL for employee_group in
        # this migration since that state causes the service to malfunction
        # noitcably and makes the service quite unusable, so it is unlikely
        # this will run into an issue in any environment it is executed. if you
        # do have employees without an employee group, update them in the
        # database or just delete them
        migrations.AlterField(
            model_name='employee',
            name='employee_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='campaign.employeegroup',
            ),
        ),
    ]
