# Generated by Django 5.0.6 on 2024-06-19 19:46

from django.db import migrations, models

import lib.storage


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0023_alter_employee_employee_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description_he',
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_welcome_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_welcome_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_welcome_text_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_subtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_subtitle_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='login_page_title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_image',
            field=lib.storage.RandomNameImageField(
                default='',
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_subtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_subtitle_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_first_banner_title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_image',
            field=lib.storage.RandomNameImageField(
                default='',
                upload_to=lib.storage.RandomNameImageField._generate_random_file_name,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_subtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_subtitle_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_sender_name',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_welcome_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_welcome_text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sms_welcome_text_he',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
