# Generated by Django 5.0.6 on 2024-06-27 07:06

from django.db import migrations, models

import campaign.models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0024_remove_campaign_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='delivery_location',
            field=models.CharField(
                choices=[('ToHome', 'to home'), ('ToOffice', 'to office')],
                default=campaign.models.DeliveryLocationEnum['ToOffice'],
                max_length=50,
            ),
        ),
    ]
