# Generated by Django 5.0.6 on 2024-07-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0025_employeegroup_delivery_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='group_campaign_product_id',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='campaign.employeegroupcampaignproduct',
            ),
        ),
    ]
