# Generated by Django 5.0.6 on 2024-07-15 21:45

from django.db import migrations, models


def update_employee_group_campaign_enum_values(apps, schema_editor):
    EmployeeGroupCampaign = apps.get_model('campaign', 'EmployeeGroupCampaign')
    db_alias = schema_editor.connection.alias

    EmployeeGroupCampaign.objects.using(db_alias).filter(
        product_selection_mode='ProductSelectionTypeEnum.SINGLE'
    ).update(product_selection_mode='SINGLE')
    EmployeeGroupCampaign.objects.using(db_alias).filter(
        product_selection_mode='ProductSelectionTypeEnum.MULTIPLE'
    ).update(product_selection_mode='MULTIPLE')

    EmployeeGroupCampaign.objects.using(db_alias).filter(
        displayed_currency='CurrencyTypeEnum.CURRENCY'
    ).update(displayed_currency='CURRENCY')
    EmployeeGroupCampaign.objects.using(db_alias).filter(
        displayed_currency='CurrencyTypeEnum.COINS'
    ).update(displayed_currency='COINS')


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0031_campaign_main_page_first_banner_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroupcampaign',
            name='displayed_currency',
            field=models.CharField(
                choices=[('COINS', 'Coins'), ('CURRENCY', 'Currency')],
                default='CURRENCY',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='employeegroupcampaign',
            name='product_selection_mode',
            field=models.CharField(
                choices=[('SINGLE', 'Single'), ('MULTIPLE', 'Multiple')],
                default='SINGLE',
                max_length=32,
            ),
        ),
        # no reverse code since the current default value is wrong and would
        # have been replaced if the value was changed via any admin form
        migrations.RunPython(update_employee_group_campaign_enum_values),
    ]
