# Generated by Django 5.0.6 on 2024-07-23 19:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0032_alter_employeegroupcampaign_displayed_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_background_color',
            field=colorfield.fields.ColorField(
                default='#C1E0CE',
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='main_page_second_banner_text_color',
            field=models.CharField(
                choices=[('BLACK', 'Black'), ('WHITE', 'White')],
                default='BLACK',
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='main_page_second_banner_image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='main_page_second_banner_mobile_image',
        ),
    ]
