# Generated by Django 5.0.6 on 2024-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0033_campaign_main_page_second_banner_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='sms_welcome_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sms_welcome_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sms_welcome_text_he',
            field=models.TextField(null=True),
        ),
    ]
