# Generated by Django 5.0.6 on 2024-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0034_alter_campaign_sms_welcome_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_subtitle_he',
            field=models.TextField(blank=True, null=True),
        ),
    ]
