# Generated by Django 5.0.6 on 2024-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0035_alter_campaign_main_page_first_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_subtitle_he',
            field=models.TextField(blank=True, null=True),
        ),
    ]
