# Generated by Django 5.0.6 on 2024-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0036_alter_campaign_main_page_second_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_first_banner_title_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='main_page_second_banner_title_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
