# Generated by Django 5.0.6 on 2024-08-08 18:08

from django.db import migrations


def fix_order_status_enum_cancelled_value(apps, schema_editor):
    Order = apps.get_model('campaign', 'Order')
    db_alias = schema_editor.connection.alias

    Order.objects.using(db_alias).filter(status='Cancelled').update(status='CANCELLED')


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0037_alter_campaign_main_page_first_banner_title_and_more'),
    ]

    operations = [
        # no reverse code since the current cancelled value is wrong and would
        # have been replaced if the value was changed via any admin form
        migrations.RunPython(fix_order_status_enum_cancelled_value),
    ]
