# Generated by Django 5.0.6 on 2024-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0039_campaign_login_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_center_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
