# Generated by Django 5.0.6 on 2024-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0042_alter_employee_auth_id_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupcampaign',
            name='check_out_location',
            field=models.CharField(
                choices=[('ISRAEL', 'Israel'), ('GLOBAL', 'Global')],
                default='ISRAEL',
                max_length=32,
            ),
        ),
    ]
