# Generated by Django 5.0.6 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0046_alter_order_color_alter_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
