# Generated by Django 5.0.6 on 2024-10-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0047_cartproduct_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
