# Generated by Django 5.0.6 on 2024-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0048_quickoffer_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickoffer',
            name='quick_offer_type',
            field=models.CharField(
                choices=[('EVENT', 'Event')], default='EVENT', max_length=30
            ),
        ),
        migrations.AlterField(
            model_name='quickoffer',
            name='ship_to',
            field=models.CharField(
                choices=[('TO_OFFICE', 'To Office'), ('TO_EMPLOYEES', 'To Employees')],
                default='TO_OFFICE',
                max_length=30,
            ),
        ),
    ]
