# Generated by Django 5.0.6 on 2024-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0049_alter_quickoffer_quick_offer_type_and_more'),
        ('inventory', '0041_product_offer_product_offer_en_product_offer_he'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOfferSelectedProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.product',
                    ),
                ),
                (
                    'quick_offer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.quickoffer',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='quickoffer',
            name='selected_products',
            field=models.ManyToManyField(
                related_name='selected_products',
                through='campaign.QuickOfferSelectedProduct',
                to='inventory.product',
            ),
        ),
    ]
