# Generated by Django 5.0.6 on 2024-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0049_quickoffertag_quickoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickoffer',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
