# Generated by Django 5.0.6 on 2024-10-24 10:29

import campaign.models
import django.db.models.deletion
import lib.phone_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0050_quickofferselectedproduct_and_more'),
        ('inventory', '0042_share_quick_offer_alter_share_campaign_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOfferOrder',
            fields=[
                ('reference', models.AutoField(primary_key=True, serialize=False)),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('SENT_TO_LOGISTIC_CENTER', 'Sent To Logistic Center')], default=campaign.models.QuickOfferOrder.OrderStatusEnum['PENDING'], max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, validators=[lib.phone_utils.validate_phone_number])),
                ('additional_phone_number', models.CharField(blank=True, max_length=255, null=True, validators=[lib.phone_utils.validate_phone_number])),
                ('delivery_city', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_street', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_street_number', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_apartment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_additional_details', models.CharField(blank=True, max_length=512, null=True)),
                ('logistics_center_status', models.CharField(blank=True, max_length=16, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('quick_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.quickoffer')),
            ],
        ),
        migrations.CreateModel(
            name='QuickOfferOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('quick_offer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.quickofferorder')),
            ],
        ),
    ]
