# Generated by Django 5.0.6 on 2024-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0052_quickofferselectedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickofferselectedproduct',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
