# Generated by Django 5.0.6 on 2024-10-31 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0053_quickofferselectedproduct_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignimpersonationtoken',
            name='quick_offer',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='campaign.quickoffer',
            ),
        ),
    ]
