# Generated by Django 5.0.6 on 2024-11-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0054_campaignimpersonationtoken_quick_offer'),
        ('inventory', '0047_product_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCampaign',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'campaign_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='campaign.campaign',
                    ),
                ),
                (
                    'tag_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='inventory.tag'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(
                through='campaign.TagCampaign', to='inventory.tag'
            ),
        ),
    ]
