# Generated by Django 5.0.6 on 2024-11-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0056_remove_quickoffer_client_status_quickofferorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickofferorderproduct',
            name='quick_offer_order',
        ),
        migrations.RemoveField(
            model_name='quickofferorderproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='quickoffer',
            name='send_my_list',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuickOfferOrder',
        ),
        migrations.DeleteModel(
            name='QuickOfferOrderProduct',
        ),
    ]
