# Generated by Django 5.0.6 on 2024-12-06 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0057_remove_quickofferorderproduct_quick_offer_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupcampaign',
            name='default_discount',
            field=models.CharField(
                choices=[('ORGANIZATION', 'organization'), ('EMPLOYEE', 'employee')],
                default='ORGANIZATION',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='employeegroupcampaignproduct',
            name='discount_mode',
            field=models.CharField(
                choices=[('ORGANIZATION', 'organization'), ('EMPLOYEE', 'employee')],
                default='ORGANIZATION',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='employeegroupcampaignproduct',
            name='organization_discount_rate',
            field=models.FloatField(
                blank=True,
                help_text='Enter a Organization Discount Rate up to 100.0.',
                null=True,
                validators=[django.core.validators.MaxValueValidator(100.0)],
            ),
        ),
    ]
