# Generated by Django 5.0.6 on 2024-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0058_employeegroupcampaign_default_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_type',
            field=models.CharField(
                blank=True,
                choices=[('EMAIL', 'email'), ('SMS', 'sms'), ('AUTH_ID', 'auth_id')],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(
                choices=[
                    ('EVENT', 'Event'),
                    ('WALLET', 'Wallet'),
                    ('NORMAL', 'Normal'),
                ],
                default='NORMAL',
                max_length=30,
            ),
        ),
    ]
