# Generated by Django 5.0.6 on 2024-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0059_employee_login_type_alter_campaign_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroupcampaign',
            name='displayed_currency',
            field=models.CharField(
                choices=[
                    ('COINS', 'Coins'),
                    ('CURRENCY', 'Currency'),
                    ('POINT', 'Point'),
                ],
                default='CURRENCY',
                max_length=32,
            ),
        ),
    ]
