# Generated by Django 5.0.6 on 2024-12-18 17:09

from django.db import migrations, models


def set_total_budget(apps, schema_editor):
    Employee = apps.get_model('campaign', 'Employee')
    EmployeeGroupCampaign = apps.get_model('campaign', 'EmployeeGroupCampaign')

    for employee in Employee.objects.all():
        employee_group_campaign = EmployeeGroupCampaign.objects.filter(
            employee_group=employee.employee_group
        ).first()

        if employee_group_campaign:
            employee.total_budget = employee_group_campaign.budget_per_employee
        else:
            employee.total_budget = 0
        employee.save()


def reverse_total_budget(apps, schema_editor):
    Employee = apps.get_model('campaign', 'Employee')
    Employee.objects.all().update(total_budget=0)


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0060_alter_employeegroupcampaign_displayed_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_total_budget, reverse_total_budget),
    ]
