# Generated by Django 5.0.6 on 2025-01-10 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0061_employee_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickofferselectedproduct',
            name='organization_discount_rate',
            field=models.FloatField(
                blank=True,
                help_text='Enter a Organization Discount Rate up to 100.0.',
                null=True,
                validators=[django.core.validators.MaxValueValidator(100.0)],
            ),
        ),
    ]
