# Generated by Django 5.0.6 on 2025-01-23 09:54

from django.db import migrations, models


def populate_total_budget(apps, schema_editor):
    CampaignEmployee = apps.get_model('campaign', 'CampaignEmployee')
    EmployeeGroupCampaign = apps.get_model('campaign', 'EmployeeGroupCampaign')

    for employee in CampaignEmployee.objects.all():
        employee_group_campaign = EmployeeGroupCampaign.objects.filter(
            employee_group=employee.employee.employee_group, campaign=employee.campaign
        ).first()

        if employee_group_campaign:
            budget = employee_group_campaign.budget_per_employee
            employee.total_budget = budget if budget else 0

            employee.save()


def reverse_total_budget(apps, schema_editor):
    CampaignEmployee = apps.get_model('campaign', 'CampaignEmployee')
    CampaignEmployee.objects.all().update(total_budget=0)


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0062_quickofferselectedproduct_organization_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='campaignemployee',
            name='total_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunPython(populate_total_budget, reverse_total_budget),
    ]
