# Generated by Django 5.0.6 on 2025-01-23 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0064_quickofferproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickoffer',
            name='products',
        ),
    ]
