# Generated by Django 5.0.6 on 2025-01-23 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0065_remove_quickoffer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickofferselectedproduct',
            name='organization_discount_rate',
        ),
    ]
