# Generated by Django 5.0.6 on 2025-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'campaign',
            '0066_remove_quickofferselectedproduct_organization_discount_rate',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignemployee',
            name='total_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
