# Generated by Django 5.0.6 on 2025-02-05 10:54

from django.db import migrations, models


def backfill_order_centers(apps, schema_editor):
    # backfill order centers - any order that was sent to a logistics center up
    # until now was sent to orian
    Order = apps.get_model('campaign', 'Order')

    for o in Order.objects.filter(status='SENT_TO_LOGISTIC_CENTER').all():
        o.logistics_center = 'ORIAN'
        o.save()


def reverse_backfill_order_centers(apps, schema_editor):
    # no need to reverse this modification since the column will be deleted
    # when other operations are reversed
    return


class Migration(migrations.Migration):
    dependencies = [
        (
            'campaign',
            '0067_alter_campaignemployee_total_budget',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_center',
            field=models.CharField(
                blank=True,
                choices=[('ORIAN', 'Orian'), ('PICK_AND_PACK', 'Pick and Pack')],
                max_length=100,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_order_centers, reverse_code=reverse_backfill_order_centers
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_center_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_center_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_center_shipping_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
