# Generated by Django 5.0.6 on 2025-02-19 12:19

from django.db import migrations, models


def fill_order_product_po_status(apps, schema_editor):
    PurchaseOrderProduct = apps.get_model('logistics', 'PurchaseOrderProduct')
    OrderProduct = apps.get_model('campaign', 'OrderProduct')
    db_alias = schema_editor.connection.alias
    for purchase_order_product in PurchaseOrderProduct.objects.using(db_alias).all():
        order_products = OrderProduct.objects.using(db_alias).filter(
            product_id__product_id=purchase_order_product.product_id
        )
        if purchase_order_product.purchase_order.status == 'PENDING':
            order_products.update(po_status='WAITING')
        if purchase_order_product.purchase_order.status == 'SENT_TO_SUPPLIER':
            order_products.update(po_status='PO_SENT')
        if purchase_order_product.purchase_order.status == 'APPROVED':
            order_products.update(po_status='IN_TRANSIT')


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0068_order_center_order_logistics_center_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='po_status',
            field=models.CharField(
                choices=[
                    ('WAITING', 'Waiting'),
                    ('PO_SENT', 'PO Sent'),
                    ('IN_TRANSIT', 'In Transit'),
                    ('COMPLETE', 'Complete'),
                ],
                default='WAITING',
                max_length=20,
            ),
        ),
        migrations.RunPython(fill_order_product_po_status),
    ]
