# Generated by Django 5.0.6 on 2025-03-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0070_employeegroupcampaignproduct_active'),
        ('logistics', '0017_add_voucher_value_to_purchaseorderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='po_status',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='purchase_order_product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='order_products',
                to='logistics.purchaseorderproduct',
            ),
        ),
    ]
