# Generated by Django 5.0.6 on 2025-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0072_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('EMAIL', 'email'),
                    ('SMS', 'sms'),
                    ('VOUCHER_CODE', 'voucher_code'),
                    ('AUTH_ID', 'auth_id'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='auth_method',
            field=models.CharField(
                choices=[
                    ('EMAIL', 'email'),
                    ('SMS', 'sms'),
                    ('VOUCHER_CODE', 'voucher_code'),
                    ('AUTH_ID', 'auth_id'),
                ],
                default='EMAIL',
                max_length=50,
            ),
        ),
    ]
