# Generated by Django 5.0.6 on 2025-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0073_alter_employee_login_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('OFFER', 'Offer'),
                    ('PREVIEW', 'Preview'),
                    ('ACTIVE', 'Active'),
                    ('PENDING_APPROVAL', 'Pending Approval'),
                    ('FINISHED', 'Finished'),
                ],
                default='PENDING',
                max_length=30,
            ),
        ),
    ]
