# Generated by Django 5.0.6 on 2025-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0074_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='raw_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
