# Generated by Django 5.0.6 on 2025-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0075_order_raw_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dc_status_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
