# Generated by Django 5.0.6 on 2025-05-09 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0076_order_dc_status_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='voucher_val',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
