# Generated by Django 5.0.6 on 2025-06-05 13:43

from django.db import migrations, models


def set_discount_mode_to_employee(apps, schema_editor):
    """
    Set discount_mode to 'EMPLOYEE' for existing EmployeeGroupCampaignProduct records
    """
    EmployeeGroupCampaignProduct = apps.get_model(
        'campaign', 'EmployeeGroupCampaignProduct'
    )

    EmployeeGroupCampaignProduct.objects.update(discount_mode='EMPLOYEE')


def reverse_set_discount_mode_to_employee(apps, schema_editor):
    """
    Reverse operation - this is generally not reversible since we don't know
    the original values, but we'll leave them as EMPLOYEE
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0078_fill_voucher_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupcampaign',
            name='company_cost_per_employee',
            field=models.IntegerField(
                default=0, verbose_name='Company Cost Per Employee'
            ),
        ),
        migrations.AlterField(
            model_name='employeegroupcampaign',
            name='budget_per_employee',
            field=models.IntegerField(verbose_name='Employee Credit'),
        ),
        migrations.RunPython(
            set_discount_mode_to_employee,
            reverse_set_discount_mode_to_employee,
        ),
    ]
