# Generated by Django 5.0.6 on 2025-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0079_employeegroupcampaign_company_cost_per_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroupcampaignproduct',
            name='company_cost_per_employee',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Company Cost Per Employee'
            ),
        ),
    ]
